# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.CharField(max_length=142, verbose_name='autor'),
        ),
    ]
